package com.varun.mobile.insight.models;

import org.springframework.data.mongodb.core.mapping.Document;

@Document("user_details")
public class UserDetail {

    //Primary key, auto generated by MongoDB
    private String _id;

    //First name of the customer
    private String firstName;

    //Last name of the customer
    private String lastName;

    //Email of the customer
    private String email;

    //Used for the login to our system
    private String password;

    public UserDetail(String firstName, String lastName, String email, String password) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.password = password;
    }

    public String get_id() {
        return _id;
    }

    public void set_id(String _id) {
        this._id = _id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}