package com.varun.mobile.insight.model;

import org.springframework.data.mongodb.core.mapping.Document;

@Document("daily_usage")
public class DailyUsage {

    //Primary key, auto generated by MongoDB
    private String _id;

    //Phone number associated with the usage
    private String mdn;

    //Customer who owns this phone number, foreign key to user collection
    private String userId;

    //ISODate("2023-10-25T00:00:00.000-0400")
    private String usageDate;

    //Usage of that day from 10-25 00:00:00 EST to 10-25 23:59:59 EST
    private int usedInMb;

    public DailyUsage(String mdn, String userId, String usageDate, int usedInMb) {
        this.mdn = mdn;
        this.userId = userId;
        this.usageDate = usageDate;
        this.usedInMb = usedInMb;
    }

    public String get_id() {
        return _id;
    }

    public void set_id(String _id) {
        this._id = _id;
    }

    public String getMdn() {
        return mdn;
    }

    public void setMdn(String mdn) {
        this.mdn = mdn;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUsageDate() {
        return usageDate;
    }

    public void setUsageDate(String usageDate) {
        this.usageDate = usageDate;
    }

    public int getUsedInMb() {
        return usedInMb;
    }

    public void setUsedInMb(int usedInMb) {
        this.usedInMb = usedInMb;
    }
}